name: Deploy to Replicate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Cog
      run: |
        wget -O /tmp/cog.tar.gz "https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64.tar.gz"
        tar -xzf /tmp/cog.tar.gz -C /tmp
        sudo mv /tmp/cog /usr/local/bin/cog
        sudo chmod +x /usr/local/bin/cog
        cog --version
        
    - name: Build and push to Replicate
      env:
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: |
        cog push r8.im/darkv5300/adverratalk2
