name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]   # จะรันทุกครั้งที่ push ไปที่ main

jobs:
  replicate:
    runs-on: ubuntu-latest

    steps:
      # ดึงโค้ดจาก repo
      - uses: actions/checkout@v4

      # ติดตั้ง cog
      - name: Install cog
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cog --user
          
          # เพิ่ม path ของ cog เข้าไป
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"

          # debug: เช็คว่า cog ติดตั้งแล้ว
          which cog || true
          cog --version || true

      # push ไปที่ Replicate
      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cog login --token $REPLICATE_API_TOKEN
          cog push r8.im/darkv5300/adverratalk
