name: Push InfiniteTalk to Replicate
on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install and Setup Cog
        run: |
          # ติดตั้ง cog
          sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
          sudo chmod +x /usr/local/bin/cog
          cog --version
      
      - name: Authenticate with Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          # สร้างไฟล์ config สำหรับ authentication
          mkdir -p ~/.config/replicate
          echo "{\"token\": \"$REPLICATE_API_TOKEN\"}" > ~/.config/replicate/config.json
      
      - name: Push to Replicate
        run: |
         cog login
cog push r8.im/darkv5300/adverratalk
