name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          cache: false

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          cog login --token $REPLICATE_API_TOKEN
          cog push r8.im/darkv5300/adverratalk
