name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog
        run: |
          python3 -m pip install --upgrade pip
          pip install cog
          echo "PATH after pip install:"
          echo $PATH
          which cog
          cog --version

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          PATH: /home/runner/.local/bin:/usr/local/bin:/usr/bin:/bin
        run: |
          echo "PATH before push:"
          echo $PATH
          which cog
          cog login --token $REPLICATE_API_TOKEN
          cog push r8.im/darkv5300/adverratalk
