name: Push InfiniteTalk to Replicate
on:
  push:
    branches: [ "main" ]   # จะรันทุกครั้งที่ push ไปที่ main

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      # ดึงโค้ดจาก repo
      - uses: actions/checkout@v4
      
      # ติดตั้ง Python (ระบุ version ให้ชัดเจน)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # ติดตั้ง cog
      - name: Install cog
        run: |
          # ติดตั้ง cog ผ่าน pip
          pip install cog
          
          # ตรวจสอบว่าติดตั้งสำเร็จ
          cog --version
      
      # push ไปที่ Replicate
      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          # Login to Replicate
          cog login --token $REPLICATE_API_TOKEN
          
          # Push model to Replicate
          cog push r8.im/darkv5300/infinitetalk
