name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # เคลียร์ pip cache ก่อน build
      - name: Clear pip cache
        run: rm -rf ~/.cache/pip

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Cog
        run: pip install cog

      - name: Deploy to Replicate
        run: cog push r8.im/darkv5300/adverratalk2
