name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cog via pip
        run: |
          python3 -m pip install --upgrade pip
          pip install cog
          cog --version

      - name: Verify Cog Config
        run: cog check

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: cog push r8.im/darkv5300/infinitetalk
