name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog (binary release)
        run: |
          curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64
          chmod +x /usr/local/bin/cog
          cog --version

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo $REPLICATE_API_TOKEN | cog login --token-stdin
          cog push r8.im/darkv5300/adverratalk
