name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog manually
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cog --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          ls -l $HOME/.local/bin || true   # debug: ดูว่า cog ลงที่นี่จริงมั้ย
          which cog || true
          cog --version || true

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          $HOME/.local/bin/cog login --token $REPLICATE_API_TOKEN
          $HOME/.local/bin/cog push r8.im/darkv5300/adverratalk
