name: replicate
on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog
        run: |
          curl -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64 -o /usr/local/bin/cog
          chmod +x /usr/local/bin/cog
          cog --version

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          cog push r8.im/darkv5300/adverratalk
