name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clear pip cache
        run: rm -rf ~/.cache/pip

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Deploy to Replicate
        run: |
          cog login --token ${{ secrets.REPLICATE_API_TOKEN }}
          cog push r8.im/darkv5300/adverratalk2
