name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ล้าง cache pip ก่อน build
      - name: Clear pip cache
        run: rm -rf ~/.cache/pip

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ติดตั้ง cog CLI จาก replicate (ไม่ใช่ pip install cog)
      - name: Install Cog
        run: |
          curl -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64.tar.gz \
          | tar xz
          sudo mv cog /usr/local/bin/cog
          cog --version

      - name: Deploy to Replicate
        run: cog push r8.im/darkv5300/adverratalk2
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
