- name: Build and push to Replicate
      env:
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: |
        docker run --rm -v "$(pwd):/src" -w /src \
          -e REPLICATE_API_TOKEN=$REPLICATE_API_TOKEN \
          replicate/cog:latest push r8.im/darkv5300/adverratalk2
