name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog (via script)
        run: |
          curl -s https://replicate.github.io/codespaces/scripts/install-cog.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          which cog
          cog --version

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cog login --token $REPLICATE_API_TOKEN
          cog push r8.im/darkv5300/adverratalk
