name: Push InfiniteTalk to Replicate

on:
  push:
    branches: [ "main" ]

jobs:
  replicate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cog
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install git+https://github.com/replicate/cog.git
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          python3 -m cog --version

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          python3 -m cog login --token $REPLICATE_API_TOKEN
          python3 -m cog push r8.im/darkv5300/adverratalk
