name: Deploy to Replicate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ดึงโค้ดจาก repo
      - uses: actions/checkout@v4

      # ติดตั้ง Cog CLI และ Auth เข้ากับ Replicate
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      # Push model ไปที่ Replicate
      - name: Push model
        run: cog push r8.im/darkv5300/adverratalk2
